### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by matchan007** [firecats/firetetris#20]
Game should start a Level 1 (Starts @ 0 on Gameboy)

Single = 100 x Level
Double = 200 x Level
Triple = 500 x Level
Tetris = 800 x Level

T-Spin Single = 400 x Level 
T-Spin Double = 800 x Level
T-Spin Triple = 1200 x Level

Back-2-Back = Score x 1.5 x Level
(only applies when you do Tetris & T-Spin consecutively without locking down a Tetrimino in-between)

**Comment by scjody** [comment]
Thanks, we'll implement this for Burning Man!
