### ISSUE TITLE
Hold Piece & Bag System

### ISSUE THREAD

**Issue by matchan007** [firecats/firetetris#22]
The single bag system seems to be working fine, but the Hold slot should be empty when the game begins. 

Also, I keep on getting confused that the hold piece is the next piece. 
The location of the Hold piece should be on the left side.

**Comment by scjody** [comment]
Thanks, we are already planning on moving the hold piece, and labeling it.  I agree it is confusing.

We'll also change it so the hold slot is empty at the start of the game.
