### ISSUE TITLE
Allow changing music

### ISSUE THREAD

**Issue by scjody** [firecats/firetetris#24]
Allow changing music via the keyboard.  A single key that goes to the next song, and a display of the current song is sufficient.  It's also fine if this only works while the game is stopped.

The game should scan a folder for any music files on startup and let the operator choose accordingly.

**Comment by mgoimam** [comment]
Folder would be pre-configured via the Config.pde, correct?

**Comment by scjody** [comment]
Yes, configuring in Config.pde is fine.

**Comment by mgoimam** [comment]
Closed by #54 features/music_selector.
