### ISSUE TITLE
"New game" flow

### ISSUE THREAD

**Issue by scjody** [firecats/firetetris#25]
The current "new game" flow needs to be improved.  How it should work:
- When the game is launched, play should **not** start immediately.  Instead a "ready to play" message should be displayed.
- Starting the game should be via a keystroke, not via the mouse.
- When the game ends, starting the next game should also be via keystroke.

**Comment by mgoimam** [comment]
Implementation will be affected by #21 (fixed by #27). Waiting for pull request to be approved to submit patch.
