### ISSUE TITLE
Add multi-player mode

### ISSUE THREAD

**Issue by mgoimam** [firecats/firetetris#4]
We want to be able to have 4+ players at the same time. Each player would be assigned one function (move left-right, rotate, hard drop).
- Might be doable using only hardware. Connect the buttons to the adapter in the same format as the NES controller.

**Comment by scjody** [comment]
Need hardware before we can start this.  Even if we build a custom controller rather than hacking a NES controller, it will be easy to do this given the changes in #13

**Comment by scjody** [comment]
I have this done - just need to test it with @mgoimam's latest input changes and submit a PR.

**Comment by mgoimam** [comment]
@scjody: We can close this now, right?

**Comment by scjody** [comment]
Yes, sorry.
