### ISSUE TITLE
Display via UDP to pre-configured server address

### ISSUE THREAD

**Issue by mgoimam** [firecats/firetetris#6]
- Depends on the protocol being defined
  *\* Could be as simple as |length|version|width|height|data| to start
- Assume server is always up and functional
- Send grid update packet every frame

**Comment by Tuizi** [comment]
I will work on this issue

**Comment by scjody** [comment]
Done by @mgoimam in #

**Comment by scjody** [comment]
Done by @Tuizi in #11
