### ISSUE TITLE
Tweak gameplay variables

### ISSUE THREAD

**Issue by mgoimam** [firecats/firetetris#9]
We want to have a fun implementation of tetris that scales nicely from easy to hard so that players of any level can play.
- Tweak the starting and maximum rate of descent of rows
- Tweak the rate increase between levels
- Tweak the length of levels (points required to graduate)
- Tweak speed of moving pieces left-right

Ideally, 2 difficulty modes (selectable from the keyboard before play starts) that we can choose from:
- Gameboy Tetris: http://tetris.wikia.com/wiki/Tetris_%28Game_Boy%29
- Tetris Grand Master: http://tetris.wikia.com/wiki/Tetris_The_Grand_Master  (Not so worried about having a perfect TGM-alike scoring system, more the timings and levels.)

The current implementation does neither of these things, so picking one and implementing it may be a good way to start.

**Comment by scjody** [comment]
@Tuizi Are you still working on this?

**Comment by scjody** [comment]
Haven't heard from @Tuizi - unassigning this.

**Comment by scjody** [comment]
Note that we don't _need_ both gameplay modes for Burning Man.  One is enough...
